- name: Install filebeat
  apt: 
    name:
      - "filebeat={{ es_version }}"
    state: present

- name: check folder
  stat:
    path: "/etc/elasticsearch/certs"
  register: checkfile

- name: create certs
  shell: 'mkdir {{ filebeat_path_cert }}'
  when: 'checkfile.stat.exists == false'

- name: add file kibana.pem
  copy:
    src: "{{ elasticsearch_local }}/elastic-certificates.pem"
    dest: "{{ filebeat_path_cert }}/kibana.pem"
    mode: 0650

- name: add file filebeat.yml
  template:
    src: filebeat.j2
    dest: "{{ filebeat_path_etc }}/filebeat.yml"
    mode: 0650

- name: Reload demon
  systemd:
    daemon_reload: yes
  notify:
    - Start filebeat
    - Enable filebeat

- name: filebeat elasticsearch
  block:
    - name: enable elasticsearch
      shell: 'filebeat modules enable elasticsearch'

    - name: add file /modules.d/elasticsearch.yml
      template:
        src: elasticsearchmodules.j2
        dest: "{{ filebeat_path_module }}/elasticsearch.yml"
        mode: 0655
  when: inventory_hostname not in groups['kibana']

- name: filebeat kibana
  block:
    - name: enable kibana
      shell: 'filebeat modules enable kibana'

    - name: add file /modules.d/kibanamodules.yml
      template:
        src: kibanamodules.j2
        dest: "{{ filebeat_path_module }}/kibana.yml"
        mode: 0655
  when: inventory_hostname not in groups['kibana']

- name: restart elasticsearch
  become: true
  shell: 'systemctl restart filebeat.service'
