---
# tasks file for roles/logstash

- name: "[Logstash] - Install Logstash"
  become: true
  apt:
    name: 
      - "logstash={{ lo_version}}"
      - nginx
      - net-tools
    state: present

- name: "[Logstash] - Fix directory permission"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ lo_owner }}"
    group: "{{ lo_groups }}"
    recurse: yes
    mode: u=rwX,g=rX,o-rwx
  loop:
    - "{{ logstash_conf_dir }}"
    - "{{ logstash_log_dir }}"
    - "{{ logstash_pid_dir }}"
    - "{{ logstash_data_dir }}"
    - "{{ logstash_certs_dir }}"

- name: Create patterns folder
  file:
    path: "{{ logstash_pat_dir }}"
    state: directory

- name: "[Logstash] - Copy elastic CA Pem logstash"
  copy:
    src: "{{ elasticsearch_local }}/http/elastic-certificates.pem"
    dest: "{{ logstash_certs_dir }}/{{ elasticsearch_ca_pem }}"
    owner: "{{ lo_owner }}"
    group: "{{ lo_groups }}"
    mode: 0644

- name: Copy elastic CA P12 logstash
  copy:
    src: "{{ elasticsearch_local }}/http/elastic-certificates.p12"
    dest: "{{ logstash_certs_dir }}/{{ elasticsearch_ca_p12 }}"
    owner: "{{ lo_owner }}"
    group: "{{ lo_groups }}"
    mode: 0644

- name: "Render logstash yml configuration file"
  template:
    src: logstash.yml.j2
    dest: "{{ logstash_conf_dir }}/logstash.yml"
    owner: "{{ lo_owner }}"
    group: "{{ lo_groups }}"
    mode: 0644
  notify:
    - reload systemd

- name: "Render logstash configuration file"
  template:
    src: logstash.conf.j2
    dest: "{{ logstash_conf_dir }}/conf.d/logstash.conf"
    owner: "{{ lo_owner }}"
    group: "{{ lo_groups }}"
    mode: 0644
    
- name: "Render logstash analytics file"
  template:
    src: nginx.j2
    dest: "{{ logstash_pat_dir }}/nginx"
  when: output_log_logstash == "yes"

- name: "Render logstash JVM configuration file"
  template:
    src: jvm.options.j2
    dest: "{{ logstash_conf_dir }}/jvm.options"
    owner: "{{ lo_owner }}"
    group: "{{ lo_groups }}"
    mode: 0644

- name: "Logstash - Daemon reload"      
  become: true
  shell: "systemctl daemon-reload"
      
- name: "Enable and start logstash"
  systemd:
    name: logstash 
    state: started 
    enabled: yes
