---

- name: ensure common
  tags: ['common']
  hosts: [ cluster, logstash ]
  become: true
  roles: [ common ]

- name: ensure elastic
  tags: ['elastic']
  gather_facts: true
  become: true
  hosts: [ elastic ]
  roles: [ elastic ]

- name: ensure kibana
  tags: ['kibana']
  become: true
  hosts: [ kibana ]
  roles: [ kibana ]
    
- name: ensure logstash
  tags: ['logstash']
  become: true
  hosts: logstash
  roles: [ logstash ]

- name: ensure beats
  tags: ['beats']
  become: true
  hosts: beats
  roles: [ beats ]

- name: uninsall elk stack
  tags: ['uninstall']
  become: true
  hosts: uninstall
  roles: [ uninstall-elk ]
