---

- name: "Ensure common"
  tags: ['common']
  hosts: [ all ]
  become: true
  roles: [ common ]

- name: "Ensure elastic"
  tags: ['elastic']
  gather_facts: true
  become: true
  hosts: [ elastic ]
  roles: [ elastic ]

- name: "Ensure kibana"
  tags: ['kibana']
  become: true
  hosts: [ kibana ]
  roles: [ kibana ]
    
- name: "Ensure logstash"
  tags: ['logsash']
  become: true
  hosts: logstash
  roles: [ logstash ]

- name: "Ensure beats"
  tags: ['beats']
  become: true
  hosts: beats
  roles: [ beats ]

- name: "Uninstall elk stack"
  tags: ['uninstall']
  become: true
  hosts: uninstall
  roles: [ uninstall-elk ]
