---

- shell: uname -s
  register: unames

- shell: uname -m
  register: unamem

- name: "Metricbeat - Install Metricbeat"
  apt: 
    name: 
      - "metricbeat={{ es_version }}"
    state: present

- name: "Metricbeat - Fix directory permission"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    mode: u=rwX,g=rX,o-rwx
  loop:
    - "{{ metricbeat_conf_dir }}"
    - "{{ metricbeat_data_dir }}"
    - "{{ metricbeat_log_dir }}"
    - "{{ metricbeat_certs_dir }}"

- name: "Metricbeat - Copy elastic CA Pem metricbeat"
  copy:
    src: "{{ elasticsearch_local }}/http/elastic-certificates.pem"
    dest: "{{ metricbeat_certs_dir }}/{{ elasticsearch_ca_pem }}"
    mode: 0644

- name: "Metricbeat - Copy elastic CA P12 metricbeat"
  copy:
    src: "{{ elasticsearch_local }}/http/elastic-certificates.p12"
    dest: "{{ metricbeat_certs_dir }}/{{ elasticsearch_ca_p12 }}"
    mode: 0644

- name: "Metricbeat - Add file metricbeat.yml"
  template:
    src: metricbeat/metricbeat.j2
    dest: "{{ metricbeat_conf_dir }}/metricbeat.yml"
    mode: 0640
  notify:
    - reload metricbeat

- name: "Metricbeat - Reload demon"
  systemd:
    daemon_reload: yes
  notify:
    - Start metricbeat
    - Enable metricbeat

- name: "Metricbeat modules elasticsearch"
  block:
    - name: "Metricbeat enable modules elasticsearch"
      shell: "metricbeat modules enable elasticsearch"

    - name: "Metricbeat add file modules /modules.d/elasticsearch.yml"
      template:
        src: metricbeat/elasticsearchmodules.j2
        dest: "{{ metricbeat_path_module }}/elasticsearch.yml"
        mode: 0640
  when: inventory_hostname in groups['elastic']

- name: "Metricbeat modules kibana"
  block:
    - name: Metricbeat enable modules elasticsearch""
      shell: "metricbeat modules enable kibana-xpack"

    - name: "Metricbeat add file modules /modules.d/kibanamodules.yml"
      template:
        src: metricbeat/kibanamodules.j2
        dest: "{{ metricbeat_path_module }}/kibana-xpack.yml"
        mode: 0640
  when: inventory_hostname in groups['kibana']

- name: "Metricbeat restart service"
  become: true
  shell: "systemctl restart metricbeat.service"
