---

- shell: uname -s
  register: unames

- shell: uname -m
  register: unamem
    
- name: "Filebeat - Install filebeat"
  apt: 
    name:
      - "filebeat={{ es_version }}"
    state: present

- name: "Filebeat - Fix directory permission"
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    mode: u=rwX,g=rX,o-rwx
  loop:
    - "{{ filebeat_conf_dir }}"
    - "{{ filebeat_data_dir }}"
    - "{{ filebeat_log_dir }}"
    - "{{ filebeat_certs_dir }}"

- name: "Filebeat - Copy elastic CA Pem filebeat"
  copy:
    src: "{{ elasticsearch_local }}/http/elastic-certificates.pem"
    dest: "{{ filebeat_certs_dir }}/{{ elasticsearch_ca_pem }}"
    mode: 0644

- name: "Filebeat - Copy elastic CA P12 filebeat"
  copy:
    src: "{{ elasticsearch_local }}/http/elastic-certificates.p12"
    dest: "{{ filebeat_certs_dir }}/{{ elasticsearch_ca_p12 }}"
    mode: 0644
      
- name: "Filebeat - Add file filebeat.yml"
  template:
    src: filebeat/filebeat.j2
    dest: "{{ filebeat_conf_dir }}/filebeat.yml"
    mode: 0640
  notify:
    - reload filebeat

- name: "Filebeat - Reload demon"
  systemd:
    daemon_reload: yes
  notify:
    - Start filebeat
    - Enable filebeat

- name: "Filebeat Modules Elasticsearch"
  block:
    - name: "Filebeat enable modules elasticsearch"
      shell: "filebeat modules enable elasticsearch"

    - name: "Filebeat add file modules /modules.d/elasticsearch.yml"
      template:
        src: filebeat/elasticsearchmodules.j2
        dest: "{{ filebeat_path_module }}/elasticsearch.yml"
        mode: 0640
  when: inventory_hostname in groups['elastic']

- name: "Filebeat Modules Kibana"
  block:
    - name: "Filebeat enable modules kibana"
      shell: "filebeat modules enable kibana"

    - name: "Filebeat add file modules /modules.d/kibanamodules.yml"
      template:
        src: filebeat/kibanamodules.j2
        dest: "{{ filebeat_path_module }}/kibana.yml"
        mode: 0640
  when: inventory_hostname in groups['kibana']

- name: "Filebeat restart service"
  become: true
  shell: 'systemctl restart filebeat.service'
