- name: Start filebeat
  service:
    name: filebeat
    state: started

- name: Restart filebeat
  service:
    name: filebeat
    state: restarted

- name: Enable filebeat
  service:
    name: filebeat
    enable: yes
