---

# Overwrite file hosts | set default
- name: "[Common] - Set new hostname for groups"
  hostname:
    name: "{{ inventory_hostname }}"

- name: "[Common] - Update hostname in {{ hostname_conf_dir }}"
  lineinfile:
    path: "{{ hostname_conf_dir }}"
    regexp: '^.*$'
    line: "{{ inventory_hostname }}"

- name: "[Common] - Overwrite hosts file with updated entries"
  become: true
  template:
    src: hosts.j2
    dest: "{{ hosts_conf_dir }}"
