--- 

- name: setup hostname
  include: hostname.yml
  tags: hostname

- name: install package
  include: package.yml
  tags: package

- name: install ssh
  include: ssh.yml
  tags: ssh

- name: install certs
  include: certs.yml
  tags: certs
  when: inventory_hostname == groups['elastic'][0]
