--- 

- name: "Setup Hostname"
  include: hostname.yml
  tags: hostname

- name: "Install Package"
  include: package.yml
  tags: package

- name: "Setup SSH"
  include: ssh.yml
  tags: ssh
  when: inventory_hostname in groups['elastic_ca']

- name: "Setup certs"
  include: certs.yml
  tags: certs
  when: inventory_hostname in groups['elastic_ca']
