---

# Update packages for cluster elk
- name: "Update system packages"
  become: true
  shell: "apt update && apt update --fix-missing -y"

- name: "Fix common Java configuration issues"
  shell: "dpkg --configure -a"

- name: "Install Java and other packages"
  apt: 
    name: 
      - openjdk-8-jdk
      - apt-transport-https
      - unzip
      - net-tools
      - nginx 
    state: present
    update_cache: yes

- name: "Check if PGP key file exists"
  stat:
    path: "{{ elasticsearch_path_keyring }}"
  register: check_gpg_key
      
- name: "Add Elasticsearch GPG key"
  shell: "wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo gpg --dearmor -o {{ elasticsearch_path_keyring }}"
  when: not check_gpg_key.stat.exists

- name: "Add Elasticsearch APT repository"
  copy:
    dest: "{{ elasticsearch_path_source }}/elastic-8.x.list"
    content: |
      deb [signed-by={{ elasticsearch_path_keyring }}] https://artifacts.elastic.co/packages/8.x/apt stable main
  become: true
  become_user: root

- name: "Update system packages cache"
  apt:
    update_cache: yes

- name: "Install Elasticsearch"
  apt: 
    name: "elasticsearch={{ es_version }}"
    state: present
  when: inventory_hostname in groups['elastic_ca']
