---

# Update packages for cluster elk
- name: "[Common] - Update system packages"
  become: true
  shell: "apt update && apt update --fix-missing -y"

- name: "[Common] - Fix common Java configuration issues"
  shell: "dpkg --configure -a"

- name: "[Common] - Install Java and other packages"
  apt: 
    name: "{{ es_package }}"
    state: present
    update_cache: yes

- name: "[Common] - Check if PGP key file exists"
  stat:
    path: "{{ elasticsearch_path_keyring }}"
  register: check_gpg_key
      
- name: "[Common] - Add Elasticsearch GPG key"
  shell: "wget -qO - {{ elasticsearch_path_gpg }} | sudo gpg --dearmor -o {{ elasticsearch_path_keyring }}"
  when: not check_gpg_key.stat.exists

- name: "[Common] - Add Elasticsearch APT repository"
  copy:
    dest: "{{ elasticsearch_path_source }}/{{ es_pack_version }}"
    content: |
      deb [signed-by={{ elasticsearch_path_keyring }}] {{ elasticsearch_path_apt }} stable main
  become: true
  become_user: "{{ owner }}"

- name: "[Common] - Update system packages cache"
  apt:
    update_cache: yes

- name: "[Common] - Install Elasticsearch"
  apt: 
    name: "{{ clustername }}={{ es_version }}"
    state: present
  when: inventory_hostname in groups['elastic_ca']
