- name: "Check if SSH key exists"
  stat:
    path: ~/.ssh/id_rsa
  register: ssh_key_file

- name: "Generate SSH key pair"
  shell: >
    ssh-keygen -q -b 4096 -t rsa -N "" -C "admin@gmail.com" -f ~/.ssh/id_rsa
  ignore_errors: true
  # run_once: true
  when: ssh_key_file.stat.exists == false

- name: "Print SSH public key"
  command: "cat ~/.ssh/id_rsa.pub"
  register: ssh_public_key
  changed_when: false

- name: "Fetch public key from the elastic node"
  fetch:
    src: "~/.ssh/id_rsa.pub"
    dest: "{{ role_path }}/files/"
    flat: yes

- name: "Add SSH Public Key to Server"
  authorized_key:
    user: root
    key: "{{ lookup('file', 'id_rsa.pub') }}"
