---

- shell: uname -s
  register: unames

- shell: uname -m
  register: unamem

- name: "Install Elasticsearch"
  apt: 
    name: "{{ clustername }}={{ es_version }}"
    state: present

- name: "Create a directory certs"
  become: true
  file: 
    path: "{{ elasticsearch_certs_dir }}"
    state: directory
    owner: "{{ es_owner }}"
    group: "{{ es_groups }}"
    mode: '2755'

- name: "Fix directory permission certs"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ es_owner }}"
    group: "{{ es_groups }}"
    recurse: yes
    mode: u=rwX,g=rX,o-rwx
  loop:
    - "{{ elasticsearch_data_dir }}"
    - "{{ elasticsearch_log_dir }}"
    - "{{ elasticsearch_pid_dir }}"
    - "{{ elasticsearch_conf_dir }}"
    - "{{ elasticsearch_certs_dir}}"

- name: "Delete files in certs folder"
  shell: "sudo rm -rf {{ elasticsearch_certs_dir }}/*"
