- name: Install Elasticsearch
  apt: 
    name: "elasticsearch={{ es_version }}"
    state: present

# - name: daemon service
#   shell: "sudo /bin/systemctl daemon-reload"
#
# - name: Ensure elasticsearch service is running
#   systemd:
#     name: elasticsearch
#     enabled: yes
#     state: started
#   register: response
#
# - name: Check elasticsearch service status
#   debug:
#     msg: "Elasticsearch service is {{ 'running' if response.changed else 'stopped' }}"
