---

- setup:
  
- name: "Check preflight task"
  include_tasks: preflight.yml

- name: "Install {{ clustername }}"
  include: install-elastic.yml

- name: "Config {{ clustername }}"
  include: config-elastic.yml
