---

lo_groups: ""
lo_owner: ""

lo_version: ""
logstash_conf_dir: ""
logstash_log_dir: ""
logstash_pid_dir: ""
logstash_certs_dir: ""
logstash_data_dir: ""
lo_port: ""
lo_jvm_xmx: ""
lo_jvm_xms: ""

elasticsearch_ca_pem: ""
elasticsearch_ca_p12: ""
elasticsearch_https_enabled: ""
elasticsearch_security_enabled: ""

